import common.data as data
import common.random_generator as random_generator
import random
from common.builder import Builder
from random import choice

builder = Builder('\"Games\"', 4)

game_names = [
"Clash Of Titans",
"Clash Of Clans",
"Clash Of Gods",
"Clash Of Angels",
"Clash Of Cities",
"Clash On Titans",
"Clash On Clans",
"Clash On Gods",
"Clash On Angels",
"Clash On Cities",
"Clash Into Titans",
"Clash Into Clans",
"Clash Into Gods",
"Clash Into Angels",
"Clash Into Cities",
"Clash From Titans",
"Clash From Clans",
"Clash From Gods",
"Clash From Angels",
"Clash From Cities",
"War Of Titans",
"War Of Clans",
"War Of Gods",
"War Of Angels",
"War Of Cities",
"War On Titans",
"War On Clans",
"War On Gods",
"War On Angels",
"War On Cities",
"War Into Titans",
"War Into Clans",
"War Into Gods",
"War Into Angels",
"War Into Cities",
"War From Titans",
"War From Clans",
"War From Gods",
"War From Angels",
"War From Cities",
"Fight Of Titans",
"Fight Of Clans",
"Fight Of Gods",
"Fight Of Angels",
"Fight Of Cities",
"Fight On Titans",
"Fight On Clans",
"Fight On Gods",
"Fight On Angels",
"Fight On Cities",
"Fight Into Titans",
"Fight Into Clans",
"Fight Into Gods",
"Fight Into Angels",
"Fight Into Cities",
"Fight From Titans",
"Fight From Clans",
"Fight From Gods",
"Fight From Angels",
"Fight From Cities",
"Attack Of Titans",
"Attack Of Clans",
"Attack Of Gods",
"Attack Of Angels",
"Attack Of Cities",
"Attack On Titans",
"Attack On Clans",
"Attack On Gods",
"Attack On Angels",
"Attack On Cities",
"Attack Into Titans",
"Attack Into Clans",
"Attack Into Gods",
"Attack Into Angels",
"Attack Into Cities",
"Attack From Titans",
"Attack From Clans",
"Attack From Gods",
"Attack From Angels",
"Attack From Cities",
"Defense Of Titans",
"Defense Of Clans",
"Defense Of Gods",
"Defense Of Angels",
"Defense Of Cities",
"Defense On Titans",
"Defense On Clans",
"Defense On Gods",
"Defense On Angels",
"Defense On Cities",
"Defense Into Titans",
"Defense Into Clans",
"Defense Into Gods",
"Defense Into Angels",
"Defense Into Cities",
"Defense From Titans",
"Defense From Clans",
"Defense From Gods",
"Defense From Angels",
"Defense From Cities"
]

for i in range(1, 101):
    print(builder.build([i, game_names[i - 1], random.randint(1, 18), i]))
